POST http://127.0.0.1:8000/api/tech/recomm HTTP/1.1
content-type: application/json
Authorization: Bearer 138|IVhsf2xq93ut4Mnb11yLWX9tTVNp7qshedTJUCdQdcf1f439

{
    "branch": "Sysu Cebu",
    "department": "Operation",
    "user": "Tomo"
}
###

GET http://127.0.0.1:8000/api/tech/recomm/1 HTTP/1.1
content-type: application/json
Authorization: Bearer 138|IVhsf2xq93ut4Mnb11yLWX9tTVNp7qshedTJUCdQdcf1f439

{

}
